services:
  mysql:
    ports:
      - "${MYSQL_PORT:-3306}:3306"

  mqtt:
    ports:
      - "${MQTT_PORT:-1883}:1883"

  mediamtx:
    ports:
      - "${MEDIA_HTTP_PORT:-8889}:8889"

  backend:
    ports:
      - "${BACKEND_HTTP_PORT:-8095}:8095"
